[[service]]
name = "postgresql"
host = "localhost"
port = 5432
executable = "local"
group = "default"
  [service.user]
  name = "git"

[[service]]
name = "redis"
host = "localhost"
port = 6379
executable = "local"
group = "default"
  [service.user]
  name = "git"

[[service]]
name = "gitaly"
host = "localhost"
port = 9999
executable = "local"
group = "default"
  [service.src]
  repo_url = "https://gitlab.com/gitlab-org/gitaly.git"
  clone_depth = 1
  [service.user]
  name = "git"

[[service]]
name = "webpack"
host = "localhost"
port = 3808
executable = "local"
group = "default"
  [service.user]
  name = "git"

[[service]]
name = "workhorse"
host = "localhost"
port = 3808
executable = "local"
group = "default"
  [service.user]
  name = "git"
  [service.src]
  repo_url = "https://gitlab.com/gitlab-org/gitlab-workhorse.git"
  clone_depth = 1

[[service]]
name = "shell"
executable = "local"
group = "default"
  [service.user]
  name = "git"

[[service]]
name = "openssh"
executable = "local"
group = "default"
  [service.user]
  name = "git"

[[service]]
name = "rails"
host = "localhost"
port = 8080
executable = "local"
group = "default"
  [service.user]
  name = "git"
  [service.src]
  repo_url = "https://gitlab.com/gitlab-org/gitlab-ce.git"
  clone_depth = 1

[[service]]
name = "sidekiq"
host = "localhost"
port = 8080
executable = "local"
group = "default"
  [service.user]
  name = "git"

[[service]]
name = "spring"
host = "localhost"
port = 8080
executable = "local"
group = "default"
  [service.user]
  name = "git"

[[service]]
name = "runner"
executable = "local"
group = "default"
  [service.user]
  name = "git"
  [service.src]
  repo_url = "https://gitlab.com/gitlab-org/gitlab-runner.git"
  clone_depth = 1
